PAGE_MAPPING = {

     '/_b_a_c_k_e_n_d/Tracker/register/':'ST-P-REG',
     '/_b_a_c_k_e_n_d/Tracker/change-password/':'ST-P-SNO',
     '/_b_a_c_k_e_n_d/Tracker/login/':'ST-P-LOG',
     '/_b_a_c_k_e_n_d/Tracker/upload-content/':'ST-P-DES',
     '/_b_a_c_k_e_n_d/Tracker/cards/':'ST-API-CRD',
     r'^/_b_a_c_k_e_n_d/Tracker/cards(?:/[^/]+)+/$':'ST-API-CRD',
     r'^/_b_a_c_k_e_n_d/Tracker/cards(?:/[^/]+)+/$':'ST-P-TDL',
     '/_b_a_c_k_e_n_d/Tracker/boards/':'ST-API-BRD',
     r'^/_b_a_c_k_e_n_d/Tracker/boards(?:/[^/]+)+/$':'ST-API-BRD',
     r'^/_b_a_c_k_e_n_d/Tracker/get-file(?:/[^/]+)+/$':'ST-P-DES',
     r'^/_b_a_c_k_e_n_d/Tracker/save-description/?(\?.*)?$':'ST-P-DES',
     '/_b_a_c_k_e_n_d/Tracker/get-files/':'ST-P-DES',
     r'^/_b_a_c_k_e_n_d/Tracker/delete-file(?:/[^/]+)+/$':'ST-P-DES',
     '/_b_a_c_k_e_n_d/Tracker/save_comment/':'ST-P-CMT',
     r'^/_b_a_c_k_e_n_d/Tracker/get_comments/?(\?.*)?$':'ST-P-CMT',
     r'^/_b_a_c_k_e_n_d/Tracker/get-boards(?:/[^/]+)+/$':'ST-P-BRD',
     '/_b_a_c_k_e_n_d/Tracker/get-employees/':'ST-API-EMP',
     r'^/_b_a_c_k_e_n_d/Tracker/add_member_to_card/?(\?.*)?$': 'ST-API-AMC',
     '/_b_a_c_k_e_n_d/Tracker/notifications/':'ST-P-NTF',
     '/_b_a_c_k_e_n_d/Tracker/delete_comment/':'ST-P-CMT',    
     '/_b_a_c_k_e_n_d/Tracker/edit_comment/':'ST-P-CMT',
     r'^/_b_a_c_k_e_n_d/Tracker/employees(?:/[^/]+)+/$':'ST-P-TDL',
     r'^/_b_a_c_k_e_n_d/Tracker/cards(?:/[^/]+)+/$':'ST-P-TDL',
     '/_b_a_c_k_e_n_d/Tracker/notifications/mark-read/':'ST-P-NTF',
  
     '/register/':'ST-P-REG',
     '/change-password/':'ST-P-SNO',
     '/login/':'ST-P-LOG',
     '/upload-content/':'ST-P-DES',
     '/cards/':'ST-API-CRD',
     '/cards/<str:card_id>/':'ST-API-CRD',
     '/cards/<str:card_id>/':'ST-P-TDL',
     '/boards/':'ST-API-BRD',
     '/boards/<int:boardId>/':'ST-API-BRD',
     '/get-file/<str:board_id>/<str:card_id>/':'ST-P-DES',
     '/save-description/':'ST-P-DES',
     '/get-files/':'ST-P-DES',
     '/delete-file/<str:board_id>/<str:card_id>/<str:filename>/':'ST-P-DES',
     '/save_comment/':'ST-P-CMT',
     '/get_comments/':'ST-P-CMT',
     '/get-boards/':'ST-P-BRD',
     '/get-employees/':'ST-API-EMP',
     '/add_member_to_card/':'ST-API-AMC',
     '/notifications/':'ST-P-NTF',
     '/delete_comment/':'ST-P-CMT',    
     '/edit_comment/':'ST-P-CMT',
     '/employees/<int:board_id>/':'ST-P-TDL',
     '/cards/<str:employee_id>/<int:board_id>/':'ST-P-TDL',
     '/notifications/mark-read/':'ST-P-NTF',
  
}

PAGE_ACTION_MAPPING = {
    'xxx': {
        'DELETE':'RWD',
    },
}

GEN_ACTION_MAPPING = {
    'POST': 'RW',
    'PUT': 'RW',
    'DELETE': 'RW',
    'GET': 'R',
    'PATCH': 'RW',
}
